version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sales
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
    ports:
      - "15432:5432"

  app:
    build: .
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: sales
      # Internal container-to-container port (Postgres listens on 5432 inside the network)
      PGPORT: 5432
      BATCH_SIZE: 10000
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.50'
    ports:
      - "3000:3000"

volumes:
  pgdata:
